name: "Build Android APK"

on:
  # Triggers the workflow when you manually run it from GitHub
  workflow_dispatch:
  # Uncomment below if you want it to run automatically when you push code
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          # Remove the cache configuration to avoid the cache error
          # cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate Android Build
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 5