name: "Build Android APK"

on:
  # Triggers the workflow when you manually run it from GitHub
  workflow_dispatch:
  # Uncomment below if you want it to run automatically when you push code
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          java-package: jdk
          # Remove the cache configuration to avoid the cache error
          # cache: "gradle"

      # Add this step to verify Java is properly set up
      - name: Verify Java Setup
        run: |
          echo "Java version:"
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Verify Java Version
        run: |
          java -version
          echo $JAVA_HOME

      - name: Generate Android Build
        run: |
          cd android
          ./gradlew -Dorg.gradle.java.home="$JAVA_HOME" assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 5